title: OpenShot OpenShot
description: Open Source Video Guides
# theme: minima  # Or 'jekyll-theme-cayman' for a clean look

site_name: Openshot
theme:
  name: material  # optional
nav:
  - Home: index.md
  - User-interface: User-interface.md
  - Converting Video: Converting-Video.md
  - Adjusting Settings: Adjusting-Settings.md
  - Troubleshooting: Troubleshooting.md

  <nav>
  <a href="/">Home</a> | <a href="/index.md/">Guide</a>
</nav>
